name: My Workflow


on:

  pull_request:

    branches: [ master ]

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v4.2.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
      - name: Install Dependencies
        run: npm i
      - name: Run Tests
        run: npm test
